init:
  - git config --global core.autocrlf input

version: '{build}'

environment:
  matrix:
    - nodejs_version: '0.10'
    - nodejs_version: '0.11'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --production
  - npm install tape
  - npm install -g rimraf

build: off

test_script:
  - ps: 'node test.js # PowerShell'
  - rimraf tmp
  - rimraf tmp_file
  - cmd: node test.js
