init:
  - git config --global core.autocrlf true

shallow_clone: true

version: '{build}'

skip_tags: true

environment:
  matrix:
    - nodejs_version: '1'
    - nodejs_version: '0.12'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --production
  - npm install read-remove-file tape

build: off

test_script:
  - ps: 'node test.js # PowerShell'
  - cmd: node test.js

cache:
  - node_modules
